services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql-container
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cadastro
      MYSQL_PASSWORD: root
    volumes:
      - ./:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    expose:
      - "3306"

  application:
    build: "./"
    container_name: crud-usuarios-container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db