
name: CRUD usuários em Java

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run project
      run: mvn spring-boot:run
