
name: CRUD usuários em Java - Deploy Ec2

on:
  push:
    branches: [ "master" ]

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: mvn clean package

    - id: deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.0
      with:
        checkout: false
        aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws_elb_app_port: 8080
